### ISSUE TITLE
flutter 客户端websocket链接保持的问题

### ISSUE THREAD

**Issue by jinfagang** [xmcy0011/CoffeeChat#2]
你的这个websocket的链接是如何保持的呢？目前来说掉线无法监听，回到HOME主界面都会导致websocket掉。

另外你的消息缓存到本地用的是sqlite吗

**Comment by xmcy0011** [comment]
你好，首先，flutter客户端目前

发自我的iPhone

**Comment by xmcy0011** [comment]
您好，针对您的疑问：
1.目前我们是使用的TCP奥，在lib/imsdk/core/business/im_client.dart的97行。`RawSocket.connect(ip, port, timeout: Duration(seconds: 5));`。
2.掉线问题的处理在im_client.dart的171行哈，读取前可以判断当前连接的状态。`void _onRead(RawSocketEvent event) {  .... if (event == RawSocketEvent.closed){...} }`
3.存储使用的sqlite，flutter里面的package名字叫sqflite

谢谢您的反馈。
